apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: prod
spec:
  replicas: 2 # Cambiar a 5 en el directorio prod
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      volumes:
      - name: html-volume
        configMap:
          name: prod-html
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-html
  namespace: prod
data:
  index.html: |
    <contenido de tu archivo index.html para prod>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: prod
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /pod-info {
            default_type application/json;
            return 200 '{"pod_name":"$hostname"}';
        }
    }
