apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: prod
spec:
  replicas: 2  # Cambiar a 5 si es necesario
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        env:  # La sección de variables de entorno estaba mal indentada o configurada
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: html-volume
        configMap:
          name: prod-html
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-html
  namespace: prod
data:
  index.html: |
    <html>
      <head>
        <title>Ambiente Prod</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            background-color: #2c3e50;
            color: #ecf0f1;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
          }
          h1 {
            color: #e74c3c;
            font-size: 2.5rem;
            margin-bottom: 10px;
          }
          p {
            font-size: 1.2rem;
          }
          pre {
            font-size: 1rem;
            color: #3498db;
            background-color: #34495e;
            padding: 10px;
            border-radius: 5px;
          }
          footer {
            position: absolute;
            bottom: 10px;
            font-size: 0.8rem;
            color: #bdc3c7;
          }
        </style>
      </head>
      <body>
        <h1>Bienvenido al Ambiente Prod</h1>
        <p>Este pod está sirviendo la solicitud:</p>
        <pre id="pod-name">Cargando...</pre>
        <script>
          fetch('/pod-info')
            .then(response => response.json())
            .then(data => {
              document.getElementById('pod-name').textContent = data.pod_name;
            });
        </script>
        <footer>Version: v1.0.0</footer>
      </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: prod
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /pod-info {
            default_type application/json;
            return 200 '{"pod_name":"$hostname"}';
        }
    }
