apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: dev # Cambiar a 'prod' en el directorio prod
spec:
  replicas: 3 # Cambiar a 5 en el directorio prod
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        emptyDir: {}
