# Versión estable (v1.0.0)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-stable
  namespace: prod
spec:
  replicas: 0  # Número de réplicas para la versión estable
  selector:
    matchLabels:
      app: nginx
      version: stable  # Etiqueta para identificar la versión estable
  template:
    metadata:
      labels:
        app: nginx
        version: stable  # Etiqueta específica para la versión estable
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Imagen válida para la versión estable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: html-volume
        configMap:
          name: stable-html
      - name: nginx-config
        configMap:
          name: nginx-config
---
# Versión Canary (v1.1.0)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-canary
  namespace: prod
spec:
  replicas: 3  # Inicialmente solo una réplica para la versión canary
  selector:
    matchLabels:
      app: nginx
      version: canary  # Etiqueta para identificar la versión canary
  template:
    metadata:
      labels:
        app: nginx
        version: canary  # Etiqueta específica para la versión canary
    spec:
      containers:
      - name: nginx
        image: nginx:1.21  # Imagen válida con cambios
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: html-volume
        configMap:
          name: canary-html
      - name: nginx-config
        configMap:
          name: nginx-config
---
# Servicio compartido entre stable y canary
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: prod
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
  type: NodePort
---
# ConfigMap para versión estable (v1.0.0)
apiVersion: v1
kind: ConfigMap
metadata:
  name: stable-html
  namespace: prod
data:
  index.html: |
    <html>
      <head>
        <title>Ambiente Stable</title>
        <style>
          body { background-color: #2ecc71; color: #fff; text-align: center; font-family: Arial, sans-serif; }
          h1 { color: #27ae60; }
          footer { margin-top: 20px; font-size: 12px; color: #ecf0f1; }
        </style>
      </head>
      <body>
        <h1>Bienvenido al Ambiente Stable</h1>
        <p>Este pod está sirviendo la solicitud:</p>
        <pre id="pod-name">Cargando...</pre>
        <script>
          fetch('/pod-info')
            .then(response => response.json())
            .then(data => {
              document.getElementById('pod-name').textContent = data.pod_name;
            });
        </script>
        <footer>Versión: v1.0.0 (Stable)</footer>
      </body>
    </html>
---
# ConfigMap para versión Canary (v1.1.0)
apiVersion: v1
kind: ConfigMap
metadata:
  name: canary-html
  namespace: prod
data:
  index.html: |
    <html>
      <head>
        <title>Ambiente Canary</title>
        <style>
          body { background-color: #e74c3c; color: #fff; text-align: center; font-family: Arial, sans-serif; }
          h1 { color: #c0392b; }
          footer { margin-top: 20px; font-size: 12px; color: #ecf0f1; }
        </style>
      </head>
      <body>
        <h1>Bienvenido al Ambiente Canary</h1>
        <p>Este pod está sirviendo la solicitud:</p>
        <pre id="pod-name">Cargando...</pre>
        <script>
          fetch('/pod-info')
            .then(response => response.json())
            .then(data => {
              document.getElementById('pod-name').textContent = data.pod_name;
            });
        </script>
        <footer>Versión: v1.1.0 (Canary)</footer>
      </body>
    </html>
---
# Configuración de NGINX compartida
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: prod
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /pod-info {
            default_type application/json;
            return 200 '{"pod_name":"$hostname"}';
        }
    }
